[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = ". .venv/bin/activate && gunicorn --bind 0.0.0.0:5000 app:app"